### ISSUE TITLE
Base Stats need updated for Gen 7

### ISSUE THREAD

**Issue by ItsASine** [lgreski/pokemonData#1]
According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Generation_VII#Alterations_from_Generation_VI), 26 Pokemon from previous generations were updated with new stat(s) in gen 7. 

For instance, Arbok's Attack is +10, from 85 to 95 as shown [in these graphs](https://bulbapedia.bulbagarden.net/wiki/Arbok_(Pok%C3%A9mon)#Base_stats)

> Twenty-six Pokémon from earlier generations receive an increase in one or more of their base stats. They are Arbok, Dugtrio, Mega Alakazam, Farfetch'd, Dodrio, Electrode, Exeggutor, Noctowl, Ariados, Qwilfish, Magcargo, Corsola, Mantine, Swellow, Pelipper, Masquerain, Delcatty, Volbeat, Illumise, Lunatone, Solrock, Chimecho, Woobat, Crustle, Beartic, Cryogonal.

**Comment by lgreski** [comment]
Thanks for the feedback, @ItsASine . I'll update the files & republish.

**Comment by lgreski** [comment]
stats refreshed from Pokemondb.net.
